#ifndef RADARE_CLIENT_GLOBAL_H
#define RADARE_CLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RADARE_CLIENT_LIBRARY)
#  define RADARE_CLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RADARE_CLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RADARE_CLIENT_GLOBAL_H
